version: '3'

services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=mariana
      - database__connection__database=ghost
    networks:
      - new-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mariana
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - new-network
volumes:
  db-data:

networks:
  new-network:
