DROP SCHEMA IF EXISTS Music;
CREATE SCHEMA IF NOT EXISTS Music;
USE Music;

CREATE TABLE tracks (
   id   INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
   name VARCHAR(100) NOT NULL,
   artist VARCHAR(100),
   album VARCHAR(100),
   duration DOUBLE NOT NULL,
   release_date DATETIME,
   inserted_by VARCHAR(100),
   tribo VARCHAR(100)
);
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Bohemian Rhapsody", "Queen", "Bohemian Rhapsody (The Original Soundtrack)", 354.947, "2018-10-19 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Riders on the Storm", "The Doors", "L.A. Woman", 434.72, "1971-04-19 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Uprising", "Muse", "The Resistance", 304.84, "2009-09-10 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Numb", "Linkin Park", "Meteora", 185.586, "2003-03-24 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ride", "Twenty One Pilots", "Blurryface", 214.506, "2015-05-15 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Tempo Perdido", "Legião Urbana", "Dois", 302.2, "1986-01-01 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ghost Division", "Sabaton", "The Art of War (Re-Armed)", 231.186, "2010-09-24 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Duality", "Slipknot", "Vol. 3: The Subliminal Verses", 252.613, "2004-01-01 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("With Or Without You", "U2", "The Best Of 1980 - 1990", 295.2, "1998-11-02 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Baba O'Riley", "The Who", "Who's Next", 300.4, "1971-08-14 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("The Ceiling", "Lewis Del Mar", "AUGUST", 174.24, "2020-08-21 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dinner & Diatribes", "Hozier", "Wasteland, Baby!", 224.146, "2019-03-01 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Até O Fim - Ao Vivo", "Engenheiros Do Hawaii", "Acústico (Ao Vivo / Deluxe)", 218.933, "2015-06-16 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Simple Man", "Lynyrd Skynyrd", "Pronounced' Leh-'Nerd 'Skin-'Nerd", 356.626, "1973-01-01 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Otherside", "Red Hot Chili Peppers", "Californication (Deluxe Edition)", 255.373, "1999-06-08 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Beautiful Day", "U2", "All That You Can't Leave Behind", 248.4, "2000-01-01 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Hit do Ano - O Peso da Luta", "MC Hariel", "Hit do Ano - O Peso da Luta", 744.727, "2021-02-05 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Friday (feat. Mufasa & Hypeman) - Dopamine Re-Edit", "Riton", "Friday (feat. Mufasa & Hypeman) [Dopamine Re-Edit]", 169.153, "2021-01-15 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Chelsea Dagger", "The Fratellis", "Chelsea Dagger (Radio Edit)", 203.76, "2006-01-01 00:00:00", "Mabiane Coimbra", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Blue Lights", "Jorja Smith", "Lost & Found", 250.454, "2018-06-08 00:00:00", "Thiago C. Amaral", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Shine On You Crazy Diamond (Pts. 1-5)", "Pink Floyd", "Wish You Were Here", 811.077, "1975-09-12 00:00:00", "lucasdolohov190", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dog Days Are Over", "Florence + The Machine", "Lungs (Deluxe Version)", 252.818, "2009-01-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Meu Pedaço de Pecado", "João Gomes", "Eu Tenho a Senha", 157.175, "2021-06-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Aquelas Coisas", "João Gomes", "Eu Tenho a Senha", 147.072, "2021-06-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Meu Bem", "João Gomes", "Meu Bem", 140.208, "2021-08-27 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Mete Um Block Nele", "João Gomes", "Eu Tenho a Senha", 177.192, "2021-06-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Se For Amor", "João Gomes", "Eu Tenho a Senha", 239.928, "2021-06-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Never Go Back - Robin Schulz Remix", "Dennis Lloyd", "Never Go Back (Remixes)", 184.652, "2019-06-07 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Jumanji", "B Young", "Jumanji", 173.153, "2018-01-05 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Basta Você Me Ligar - Ao Vivo", "Os Barões Da Pisadinha", "Conquistas - EP 1 (Ao Vivo)", 182.976, "2020-05-29 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ecstasy", "Veeiye", "Ecstasy", 176.065, "2017-03-27 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Enemy (with JID) - from the series Arcane League of Legends", "Imagine Dragons", "Enemy (with JID) [from the series Arcane League of Legends]", 173.381, "2021-10-28 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Billionaire (feat. Bruno Mars)", "Travie McCoy", "Billionaire (feat. Bruno Mars)", 211.16, "2010-03-09 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("The Lazy Song", "Bruno Mars", "Doo-Wops & Hooligans", 189.109, "2010-10-05 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Thunderstruck", "AC/DC", "The Razors Edge", 292.88, "1990-09-24 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Man in the Box", "Alice In Chains", "Facelift", 285.2, "1990-08-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Smells Like Teen Spirit", "Nirvana", "Nevermind (Remastered)", 301.92, "1991-09-26 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Freak On a Leash", "Korn", "Follow The Leader", 255.733, "1998-08-18 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dragula", "Rob Zombie", "Hellbilly Deluxe", 222.826, "1998-01-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Break Stuff", "Limp Bizkit", "Significant Other", 166.706, "1999-01-01 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dance Of Death", "Iron Maiden", "From Fear to Eternity: The Best of 1990 - 2010", 517.173, "2011-06-06 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Nothing Else Matters", "Metallica", "Metallica", 388.266, "1991-08-12 00:00:00", "Renato Álvares", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Hey Jude - Remastered 2015", "The Beatles", "1 (Remastered)", 425.653, "2000-11-13 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Seven Nation Army", "The White Stripes", "Elephant", 232.106, "2003-04-01 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Walk", "Foo Fighters", "Wasting Light", 255.96, "2011-04-12 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Can't Stop", "Red Hot Chili Peppers", "By the Way (Deluxe Edition)", 269, "2002-07-09 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Californication", "Red Hot Chili Peppers", "Californication (Deluxe Edition)", 329.733, "1999-06-08 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Paradise City", "Guns N' Roses", "Appetite For Destruction", 405.64, "1987-07-21 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dani California", "Red Hot Chili Peppers", "Stadium Arcadium", 282.16, "2006-05-09 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("By the Way", "Red Hot Chili Peppers", "By the Way (Deluxe Edition)", 216.933, "2002-07-09 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Welcome To The Jungle", "Guns N' Roses", "Appetite For Destruction", 272.026, "1987-07-21 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("All My Life", "Foo Fighters", "One By One (Expanded Edition)", 263.44, "2002-10-22 00:00:00", "Rafaela", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("This Must Be the Place (Naive Melody) - 2005 Remaster", "Talking Heads", "Speaking in Tongues (Deluxe Version)", 296.146, "1983-05-31 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("15 Step", "Radiohead", "In Rainbows", 237.293, "2007-12-28 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Mother We Just Can't Get Enough", "New Radicals", "Maybe You've Been Brainwashed Too", 346.066, "1998-01-01 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Shout", "Tears For Fears", "Songs From The Big Chair", 393.666, "1985-02-25 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Gold", "Chet Faker", "Built on Glass", 285.255, "2014-04-14 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Gigantic", "Pixies", "Wave of Mutilation: Best of Pixies", 193.546, "2004-05-03 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Come Out and Play", "The Offspring", "Smash", 197.8, "1994-04-08 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("All For Us - from the HBO Original Series Euphoria", "Labrinth", "All For Us (from the HBO Original Series Euphoria)", 192.986, "2019-08-04 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Mount Everest", "Labrinth", "Imagination & the Misfit Kid", 157.497, "2019-11-22 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Meet Me At Our Spot - Live", "THE ANXIETY", "Meet Me At Our Spot (Live)", 147.828, "2021-10-22 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Come A Little Closer", "Cage The Elephant", "Melophobia", 229.346, "2013-10-08 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Trouble", "Cage The Elephant", "Tell Me I'm Pretty", 225.973, "2015-12-18 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Paranoid Android", "Radiohead", "OK Computer", 387.213, "1997-05-28 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("The Man Who Sold The World", "Nirvana", "MTV Unplugged In New York", 261.093, "1994-11-01 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("American Pie", "Don McLean", "American Pie", 516.893, "1971-01-01 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("American Idiot", "Green Day", "American Idiot", 176.346, "2004-09-21 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Hand in My Pocket - 2015 Remaster", "Alanis Morissette", "Jagged Little Pill (2015 Remaster)", 222.013, "1995-01-01 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ironic - 2015 Remaster", "Alanis Morissette", "Jagged Little Pill (2015 Remaster)", 230, "1995-01-01 00:00:00", "Priscila Silva", "A");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Torn", "Natalie Imbruglia", "Left Of The Middle", 244.666, "1997-11-10 00:00:00", "Priscila Silva", "A");

INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Best of You", "Foo Fighters", "In Your Honor", 255.626, "2005-06-14 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Lose Yourself", "Eminem", "SHADYXV", 320.626, "2014-11-24 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Maracatu Atômico", "Chico Science", "Afrociberdelia", 284.173, "1996-05-15 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Nothing Else Matters", "Metallica", "Metallica", 388.266, "1991-08-12 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Meteor Gardens", "Devilmaycry", "These Secrets Will Kill Us", 170, "2019-02-13 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("I Apologize", "Five Finger Death Punch", "Got Your Six", 242.956, "2015-09-04 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sweet Home Alabama", "Lynyrd Skynyrd", "Second Helping", 283.8, "1974-04-15 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ain't No Rest For The Wicked - Original Version", "Cage The Elephant", "Cage The Elephant", 175.493, "2008-01-01 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Paint It, Black", "The Rolling Stones", "Aftermath", 202.266, "1966-04-15 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Buttercup", "Jack Stauber", "Pop Food", 208.026, "2017-03-25 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Back In The Game", "Airbourne", "Black Dog Barking (Special Edition)", 205.506, "2013-05-17 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("POWER", "Kanye West", "My Beautiful Dark Twisted Fantasy", 292.093, "2010-11-22 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("The Cave", "Mumford & Sons", "Sigh No More", 215.626, "2009-01-01 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Shout", "Tears For Fears", "Songs From The Big Chair", 393.666, "1985-02-25 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Little Lion Man", "Mumford & Sons", "Sigh No More", 245.173, "2009-01-01 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Bohemian Rhapsodie", "Royal Philharmonic Orchestra", "Queen's Rhapsody - The Hits Of Queen", 361.093, "1992-01-27 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Bulls On Parade", "Rage Against The Machine", "Evil Empire", 229.466, "1996-04-16 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("A Lizard State", "King Krule", "6 Feet Beneath the Moon", 259.746, "2013-08-24 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Communication Breakdown - 1990 Remaster", "Led Zeppelin", "Led Zeppelin", 147.933, "1969-01-12 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Heat Above", "Greta Van Fleet", "Broken Bells", 341.255, "2021-03-19 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Blitzkrieg Bop", "Ramones", "Dia Mundial do Rock!", 133.44, "2020-07-13 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Told You So - A Tribute to Leslie Clio", "Colossal Music", "Told You So (A Tribute to Leslie Clio)", 184.502, "2013-04-10 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ghost Town", "Kanye West", "ye", 271.386, "2018-06-01 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Yours Is No Disgrace - 2003 Remaster", "Yes", "The Yes Album (Deluxe Edition)", 580.96, "1971-02-19 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Laugh Now Cry Later (feat. Lil Durk)", "Drake", "Laugh Now Cry Later (feat. Lil Durk)", 261.492, "2020-08-14 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dirty Paws", "Of Monsters and Men", "My Head Is An Animal", 278.373, "2012-01-01 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dream On", "Aerosmith", "Aerosmith", 266.96, "1973-01-05 00:00:00", "Karina", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Anjos (Pra quem tem fé)", "O Rappa", "Nunca Tem Fim (Standard)", 419.52, "2013-08-15 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Love Generation - Radio Edit", "Bob Sinclar", "Love Generation (Radio Edit)", 204.798, "2005-06-20 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Pontes Indestrutíveis", "Charlie Brown Jr.", "Ritmo, Ritual E Responsa", 210.666, "2007-03-10 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Minha alma (A paz que eu não quero)", "O Rappa", "Lado B Lado A", 303.773, "1999-01-01 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Smells Like Teen Spirit", "Nirvana", "Nevermind (Deluxe Edition)", 301.92, "1991-09-26 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Livin' On A Prayer", "Bon Jovi", "Slippery When Wet", 249.293, "1986-08-16 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Thunderstruck", "AC/DC", "The Razors Edge", 292.88, "1990-09-24 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Better Together", "Jack Johnson", "In Between Dreams", 207.68, "2005-01-01 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Banana Pancakes", "Jack Johnson", "In Between Dreams", 191.906, "2005-01-01 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Upside Down", "Jack Johnson", "Upside Down", 209.546, "2006-02-24 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sitting, Waiting, Wishing", "Jack Johnson", "In Between Dreams", 183.72, "2005-01-01 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sunsets For Somebody Else", "Jack Johnson", "All The Light Above It Too", 210.466, "2017-09-08 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Fear of the Dark - 2015 Remaster", "Iron Maiden", "Fear of the Dark (2015 Remaster)", 438.12, "1992-01-01 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("I'm Scum", "IDLES", "Joy as an Act of Resistance.", 189.976, "2018-08-31 00:00:00", "Leonardo Machado", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Crack Rock", "Frank Ocean", "channel ORANGE (Explicit Version)", 224.146, "2012-07-10 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Eventually", "Tame Impala", "Currents", 318.591, "2015-07-17 00:00:00", "Marllon Martins", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("A Forest", "The Cure", "Seventeen Seconds", 354.64, "1980-04-18 00:00:00", "Marllon Martins", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Good Song", "Blur", "Think Tank (Special Edition)", 187.68, "2003-01-01 00:00:00", "Marllon Martins", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("t r a n s p a r e n t s o u l feat. Travis Barker", "WILLOW", "lately I feel EVERYTHING", 168.398, "2021-07-16 00:00:00", "Marllon Martins", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Passionfruit", "Drake", "More Life", 298.94, "2017-03-18 00:00:00", "Marllon Martins", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Woman", "Wolfmother", "Wolfmother", 176.306, "2006-01-01 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("N.I.B.", "Black Sabbath", "Black Sabbath (Remastered)", 366.4, "1970-02-13 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Follow God", "Kanye West", "JESUS IS KING", 104.591, "2019-10-25 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Violin Sonata in G Minor Devils Trill: I. Larghetto affetuoso - Allegro", "Giuseppe Tartini", "Tartini: Devil's Trill Sonata; Violin Concertos D12, D51, D80, & D115", 410.906, "2015-03-31 00:00:00", "22i3scg7wazsosc4mx7rwkmeq", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Aquemini", "Outkast", "Aquemini", 319.24, "1998-09-29 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Nocturnes, Op. 9: No. 1 in B flat major. Larghetto", "Frédéric Chopin", "Chopin: Complete Nocturnes", 352.8, "2010-06-22 00:00:00", "22i3scg7wazsosc4mx7rwkmeq", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Nights", "Frank Ocean", "Blonde", 307.151, "2016-08-20 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("SWEET / I THOUGHT YOU WANTED TO DANCE (feat. Brent Faiyaz & Fana Hues)", "Tyler, The Creator", "CALL ME IF YOU GET LOST", 588.139, "2021-06-25 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Rock with You - Single Version", "Michael Jackson", "Off the Wall", 220.626, "1979-08-10 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("EARFQUAKE", "Tyler, The Creator", "IGOR", 190.066, "2019-05-17 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Runaway", "Kanye West", "My Beautiful Dark Twisted Fantasy", 547.733, "2010-11-22 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Black Skinhead", "Kanye West", "Yeezus", 188.013, "2013-06-18 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Playground", "Steve Lacy", "Apollo XXI", 213.797, "2019-05-24 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Hold On", "The Internet", "Hive Mind", 406.466, "2018-07-20 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("REVOFEV", "Kid Cudi", "Man On The Moon II: The Legend Of Mr. Rager", 183.173, "2010-11-09 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Every Rose Has Its Thorn", "Poison", "Open Up And Say . . . Ahh!", 260.224, "1988-05-03 00:00:00", "luks_bc", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Move on Up", "Curtis Mayfield", "Move on Up", 165.789, "1970-01-01 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Today - 2011 Remaster", "The Smashing Pumpkins", "Siamese Dream (2011 - Remaster)", 201.173, "1993-07-27 00:00:00", "Hlremanuel", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Angouleme", "Metá Metá", "M M 3", 121.134, "2016-05-25 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Silent Lucidity", "Queensrÿche", "Hear In The Now Frontier (Remastered)", 324.573, "2003-01-01 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Bicycle Race - Remastered 2011", "Queen", "Jazz (2011 Remaster)", 180.813, "1978-11-10 00:00:00", "Natashia Romanzini", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sins of The Father", "Donna Burke", "METAL GEAR SOLID Ⅴ ORIGINAL SOUNDTRACK SELECTION", 294, "2015-09-02 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Nuclear", "Mike Oldfield", "Man On The Rocks", 303.986, "2014-01-01 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Hurt", "Johnny Cash", "American IV: The Man Comes Around", 216.533, "2002-01-01 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Principia (feat. Fabiana Cozza, Pastor Henrique Vieira & Pastoras do Rosário)", "Emicida", "AmarElo", 355.866, "2019-10-30 00:00:00", "Alissandra", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Doo Wop (That Thing)", "Ms. Lauryn Hill", "The Miseducation of Lauryn Hill", 320.266, "1998-08-25 00:00:00", "Alissandra", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sobre Nós", "Drik Barbosa", "Sobre Nós", 219.6, "2020-11-12 00:00:00", "Alissandra", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Flor de Tangerina", "Alceu Valença", "Flor de Tangerina - Single", 181.869, "2016-04-22 00:00:00", "Alissandra", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Flor de Aruanda - Citação: Feminina", "Rael", "Capim-Cidreira", 183.146, "2019-09-12 00:00:00", "Alissandra", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Superhero", "Unknown Brain", "Superhero", 179.224, "2016-11-26 00:00:00", "luks_bc", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Go With The Flow", "Queens of the Stone Age", "Songs For The Deaf", 187.146, "2002-01-01 00:00:00", "Hlremanuel", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Gorgeous", "Kanye West", "My Beautiful Dark Twisted Fantasy", 357.653, "2010-11-22 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("In My Room", "Frank Ocean", "In My Room", 133.68, "2019-11-02 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Chanel", "Frank Ocean", "Chanel", 210.285, "2017-03-10 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("PRIDE.", "Kendrick Lamar", "DAMN.", 275.253, "2017-04-14 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Gravity (feat. Tyler, The Creator)", "Brent Faiyaz", "Gravity (feat. Tyler, The Creator)", 214.692, "2021-01-29 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Little Dark Age", "MGMT", "Little Dark Age", 299.96, "2018-02-09 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("On Melancholy Hill", "Gorillaz", "Plastic Beach", 233.866, "2010-03-03 00:00:00", "Rael", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Attitude", "Bad Brains", "Bad Brains", 79.853, "1982-01-01 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Wild Blue", "John Mayer", "Sob Rock", 252.413, "2021-07-16 00:00:00", "Arthur", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Shot in the Dark", "John Mayer", "Sob Rock", 249.08, "2021-07-16 00:00:00", "Arthur", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Why You No Love Me", "John Mayer", "Sob Rock", 255.213, "2021-07-16 00:00:00", "Arthur", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Shouldn't Matter but It Does", "John Mayer", "Sob Rock", 236.733, "2021-07-16 00:00:00", "Arthur", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Inside Friend (feat. John Mayer)", "Leon Bridges", "Inside Friend (feat. John Mayer)", 175.432, "2020-04-10 00:00:00", "Arthur", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Howlin' For You", "The Black Keys", "Brothers (Deluxe Edition)", 191.8, "2010-10-18 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Human After All", "Daft Punk", "Human After All", 319.879, "2005-03-14 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Lose Yourself to Dance (feat. Pharrell Williams)", "Daft Punk", "Random Access Memories", 353.893, "2013-05-17 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Technologic", "Daft Punk", "Human After All", 284.28, "2005-03-14 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Table For 2", "Alok", "Table For 2", 176.283, "2019-09-27 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Mad World", "Timmy Trumpet", "Mad World", 153.303, "2020-11-13 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Don't Stop Me Now - Remastered 2011", "Queen", "Jazz (2011 Remaster)", 209.413, "1978-11-10 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Back In Black", "AC/DC", "Back In Black", 255.493, "1980-07-25 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sweet Dreams (Are Made of This) - Remastered", "Eurythmics", "Sweet Dreams (Are Made Of This)", 216.933, "1983-01-04 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("These Boots Are Made For Walkin'", "Nancy Sinatra", "Boots", 166.008, "1966-03-01 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Me and Your Mama", "Childish Gambino", "Awaken, My Love!", 379.226, "2016-12-02 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("International Feel - 2015 Remaster", "Todd Rundgren", "A Wizard / A True Star", 170.133, "1972-01-01 00:00:00", "natanarozi", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Jail", "Kanye West", "Donda", 297, "2021-08-29 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Junya", "Kanye West", "Donda", 147.668, "2021-08-29 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Believe What I Say", "Kanye West", "Donda", 242.4, "2021-08-29 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Moon", "Kanye West", "Donda", 156.091, "2021-08-29 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ok Ok pt 2", "Kanye West", "Donda", 204.629, "2021-08-29 00:00:00", "Brunao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Repetition", "Information Society", "Information Society", 274.626, "1988-06-21 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Running", "Information Society", "Information Society", 466.8, "1988-06-21 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Bent to Fly", "Slash", "World on Fire", 296.706, "2014-09-08 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Whisper Whisper", "Bee Gees", "Odessa", 206.6, "1969-03-30 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Shooting Stars", "Bag Raiders", "Bag Raiders (Deluxe)", 235.813, "2011-01-01 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("I Am Machine", "Three Days Grace", "Human", 200.146, "2015-03-27 00:00:00", "Flávio A.", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dancing With Myself", "Billy Idol", "Vital Idol", 359.733, "1985-01-01 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Let's Go! - Original Extended Mix", "DJ Rebel", "DJ's 12 Club Tunes Miami 2013 Edition", 363.75, "2013-03-16 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Fuego", "Alok", "Fuego", 188.852, "2017-02-27 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Byob", "Sevenn", "Byob", 259.693, "2016-05-10 00:00:00", "Izabela.Hammer", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Não Me Sinto Mal Mais", "Sidoka", "Não Me Sinto Mal Mais", 265.355, "2019-10-18 00:00:00", "Bruno Marques", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Feeling Good", "Nina Simone", "I Put A Spell On You", 174, "1965-06-01 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Like a Stone", "Audioslave", "Audioslave", 293.96, "2002-11-17 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("I Am Mine", "Pearl Jam", "Riot Act", 215.333, "2002-11-08 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("My Sacrifice - Radio Edit", "Creed", "With Arms Wide Open: A Retrospective", 259.666, "2015-01-01 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Black - Kaufman Astoria Studios - MTV Unplugged - New York, NY 3/16/1992", "Pearl Jam", "Pearl Jam Twenty Original Motion Picture Soundtrack", 339.96, "2011-09-16 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Snuff", "Slipknot", "All Hope Is Gone", 276.146, "2008-08-22 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Through Glass", "Stone Sour", "Come What(ever) May [10th Anniversary Edition]", 282.946, "2006-01-01 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Dear God", "Avenged Sevenfold", "Avenged Sevenfold", 393.48, "2007-10-26 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Let Me Down", "Jorja Smith", "Let Me Down", 188, "2018-01-12 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Novacaine", "10 Years", "(how to live) AS GHOSTS", 169.52, "2017-10-27 00:00:00", "Renata Magno", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("When You Die", "MGMT", "Little Dark Age", 263.88, "2018-02-09 00:00:00", "Gab_", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Movie", "Chris Goma", "Movie", 202.607, "2022-01-12 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("I've Got All This Ringing In My Ears And None On My Fingers", "Fall Out Boy", "Infinity On High", 246.533, "2007-01-01 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("For Once In My Life", "Stevie Wonder", "For Once In My Life", 169.8, "1968-12-01 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Budapest", "George Ezra", "Wanted on Voyage", 200.72, "2014-06-27 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Psycho Killer - 2005 Remaster", "Talking Heads", "Talking Heads '77 (Deluxe Version)", 261.413, "1977-09-16 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Down in the Valley", "The Head And The Heart", "The Head and the Heart", 303.653, "2011-04-18 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("LAst dAy oN EaRTh", "Tai Verdes", "LAst dAy oN EaRTh", 172.755, "2022-01-13 00:00:00", "Gilson", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Open Your Eyes", "Alter Bridge", "One Day Remains", 298.6, "2004-08-10 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Broken Wings", "Alter Bridge", "One Day Remains", 306.6, "2004-08-10 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Enter Sandman", "Metallica", "Metallica", 331.266, "1991-08-12 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Ace of Spades", "Motörhead", "Ace of Spades (Expanded Edition)", 166.92, "1980-11-08 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Still Loving You", "Scorpions", "Comeblack", 403.453, "2011-11-04 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Rock You Like A Hurricane", "Scorpions", "Love At First Sting", 252.493, "1984-03-27 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("No One Like You", "Scorpions", "Blackout", 237.466, "1982-04-10 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Hearts on Fire", "HammerFall", "Crimson Thunder", 231.386, "2002-10-28 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Sweet Child O' Mine", "Guns N' Roses", "Appetite For Destruction", 354.52, "1987-07-21 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Heaven", "Bryan Adams", "Reckless (30th Anniversary / Deluxe Edition)", 243.36, "1984-11-05 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Here I Go Again - 2011 Remaster", "Whitesnake", "Saints and Sinners (2013 Remaster)", 308.24, "1982-11-20 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Boulevard of Broken Dreams", "Neck Deep", "Boulevard of Broken Dreams", 220, "2014-06-17 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("The Bard's Song - In the Forest - Remastered 2007", "Blind Guardian", "Somewhere Far Beyond (Remastered 2007)", 189.893, "1992-06-30 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Wanted Dead Or Alive", "Bon Jovi", "Slippery When Wet", 308.666, "1986-08-16 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Living on a Prayer", "No Bragging Rights", "Living on a Prayer - Single", 241.586, "2009-01-01 00:00:00", "Grazziano Borges Fagundes", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Feel It Still", "Portugal. The Man", "Woodstock", 163.253, "2017-06-16 00:00:00", "Pedro Brandao", "B");
INSERT  INTO tracks(name, artist, album, duration, release_date, inserted_by, tribo) VALUES ("Skyfall", "Our Last Night", "Age Of Ignorance (Deluxe Edition)", 249.411, "2013-06-18 00:00:00", "Renata Magno", "B");

COMMIT;